spring:
  profiles:
    group:
      blue: blue, common, secret-dev
      green: green, common, secret-dev

server:
  env: blue

---

server:
  port: 8080
  serverAddress: 13.124.174.27

serverName: blue_server_dev

spring:
  config:
    activate:
      on-profile: blue

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create-drop

---

server:
  port: 8081
  serverAddress: 13.124.174.27

serverName: green_server_dev

spring:
  config:
    activate:
      on-profile: green
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create-drop
