spring:
  profiles:
    group:
      blue: blue, common, secret-prod
      green: green, common, secret-prod

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: common

  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: https://linkit.im/login/oauth2/callback/naver
          kakao:
            redirect-uri: https://linkit.im/login/oauth2/callback/kakao
          google:
            redirect-uri: https://linkit.im/login/oauth2/callback/google

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: validate

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  sql:
    init:
      mode: never

  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원 여부
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      max-file-size: 60MB # 한 개 파일의 최대 사이즈
      max-request-size: 60MB # 한 개 요청의 최대 사이즈

logging:
  level:
    root: WARN                     # 기본 WARN 레벨 (불필요한 정보 최소화)
    liaison.swagger_test: INFO     # 애플리케이션 코드는 INFO 유지
    org.springframework: WARN      # 프레임워크 로그는 WARN
    org.springframework.security: INFO # 보안 관련 로그는 INFO
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [request_id=%X{request_id}] [client_ip=%X{client_ip}] [user_id=%X{user_id}] [env=prod] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [request_id=%X{request_id}] [client_ip=%X{client_ip}] [user_id=%X{user_id}] [env=prod] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/application/application.log  # 표준 리눅스 로그 경로
  logback:
    rollingpolicy:
      max-file-size: 500MB         # 더 큰 파일 크기
      file-name-pattern: /var/log/application/application-%d{yyyy-MM-dd}-%i.log
      max-history: 90              # 분기별 보관 (약 3개월)
      total-size-cap: 20GB         # 더 많은 로그 보관

decorator:
  datasource:
    p6spy:
      enable-logging: false

springdoc:
  webjars:
    prefix:
  api-docs:
    path: /linkit/api-docs
    groups:
      enabled: true
  swagger-ui:
    urls:
      - url: /linkit/api-docs
        name: all
    path: /linkit/swagger
    configUrl: /linkit/api-docs/swagger-config
    disable-swagger-default-url: true
