spring:
  profiles:
    group:
      blue: blue, common, secret-dev
      green: green, common, secret-dev

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: common

  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: https://liaison-dev.site/login/oauth2/callback/naver
          kakao:
            redirect-uri: https://liaison-dev.site/login/oauth2/callback/kakao
          google:
            redirect-uri: https://liaison-dev.site/login/oauth2/callback/google

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 100
        generate_statistics: true   # 성능 모니터링 설정
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: validate

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  sql:
    init:
      mode: never

  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원 여부
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      max-file-size: 60MB # 한 개 파일의 최대 사이즈
      max-request-size: 60MB # 한 개 요청의 최대 사이즈

decorator:
  datasource:
    p6spy:
      enable-logging: false
      multiline: false
      logging: slf4j

logging:
  level:
    root: INFO
    liaison.swagger_test: INFO
    #    org.springframework.web: INFO
    org.springframework.batch: INFO
    # 기타 로그 레벨 설정...
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [request_id=%X{request_id}] [client_ip=%X{client_ip}] [user_id=%X{user_id}] [env=${server.env}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [request_id=%X{request_id}] [client_ip=%X{client_ip}] [user_id=%X{user_id}] [env=${server.env}] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/application-${server.env}.log  # 환경 변수 활용
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 1GB

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**
  packages-to-scan:
    - liaison.linkit

app:
  backend-url: https://dev.liaison-dev.site
