
ALTER TABLE team_matching
ADD COLUMN is_sender_check BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE team_matching
ADD COLUMN is_receiver_check BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE private_matching
ADD COLUMN is_sender_check BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE private_matching
ADD COLUMN is_receiver_check BOOLEAN NOT NULL DEFAULT FALSE;
